apiVersion: v1
kind: ConfigMap
metadata:
  name: marks-config
data:
  DB_HOST: mysql
  DB_USER: gms_user
  DB_NAME: marks
  DB_PORT: "3306"
  COURSES_SERVICE_URL: "http://courses:8080"
  ANALYTICS_SERVICE_URL: "http://analytics:7000"