CREATE USER 'gms_user'@'%' IDENTIFIED BY 'GmsUserPass123';

CREATE DATABASE auth;

GRANT ALL PRIVILEGES ON auth.* TO 'gms_user'@'%';

USE auth;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    password_hash VARCHAR(256) NOT NULL,
    email VARCHAR(128) NOT NULL UNIQUE,
    last_login TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE feedback (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    feedback_text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);