apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-config
data:
  DB_HOST: mysql
  DB_USER: gms_user
  DB_NAME: policy
  DB_PORT: "3306"
  MARKS_SERVICE_URL: "http://marks:6000"
  COURSES_SERVICE_URL: "http://courses:8080"
  COMPUTE_QUEUE: "compute_total"